name: 'Deploy'

on:
  push:
    branches: [ production ]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Get Checkout
        uses: actions/checkout@v2

      - name: Verify Workspace
        run: |
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
      - name: Verify Folder
        run: |
          ls -lah ${GITHUB_WORKSPACE}

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc -i"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/home/jorjafox/jorjafox.net/wordpress/wp-content/plugins/jorjafox/"
          EXCLUDE: "/.git/, /.github/"
